feat: Add region/country support for client and user models
isFakeAccount/psnawp pull request #95
Opened 2024-11-15 20:08 UTC by Dev-R

Add functionality to accurately fetch and display a user's region or country in the `client` and `user` models.

## Changes
- Added region/country attributes to the `client` and `user` models.
- Updated documentation to reflect the new feature.

## References
- Resolves [#90](https://github.com/isFakeAccount/psnawp/issues/90): Fetch user’s country.
- Addresses [#83](https://github.com/isFakeAccount/psnawp/discussions/83): Region endpoint support.

## Sample
- ![image](https://github.com/user-attachments/assets/009c8d54-2e71-417c-8a63-d6fe1cd56ad6)

2025-01-06 00:16 UTC, isFakeAccount requested changes
Also, if you are able to add test that would be nice.

2025-01-06 00:30 UTC, isFakeAccount commented on src/psnawp_api/utils/misc.py
> +DECODED_NPID_PATTERN = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
since the last two characters of the string are going to be ISO 3166-1 alpha-2 you might not need regex. 

Compare the regex to simply slicing last two characters. I think slicing will be faster.

2025-01-06 00:30 UTC, isFakeAccount commented on src/psnawp_api/utils/misc.py
> +        return match.group(1).upper() if match and match.group(1) else None
Look into https://github.com/pycountry/pycountry. Might be interesting. Easier to parse for someone who doesn't know the ISO 3166-1 alpha-2 country codes.

2025-01-06 00:30 UTC, isFakeAccount commented on src/psnawp_api/utils/misc.py
> +DECODED_NPID_PATTERN = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

2025-01-11 20:39 UTC, Dev-R commented on src/psnawp_api/utils/misc.py
> +        return match.group(1).upper() if match and match.group(1) else None
Good suggestion! I just wanted to avoid adding further dependencies.

2025-01-12 03:40 UTC, isFakeAccount approved these changes

2025-01-12 03:55 UTC, merged